name: Generate HTML

on:
  push:
    branches:
      - main

jobs:
  show-table:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: curl https://raw.githubusercontent.com/[your-username]/[your-repo]/master/[your-html-file].html
