name: Generate HTML

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch file from repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install csvkit

      - name: Process data and generate HTML
        run: |
          python process_data.py

      - name: Publish HTML content
        run: |
          htmlContent=$(python process_data.py)
          echo "$htmlContent" > html_content.html
          git config --global user.email "devesh.joshi@philips.com"
          git config --global user.name "devesh-joshi"
          git add html_content.html
          git commit -m "Publish HTML content"
          git push

      - name: Show HTML content
        run: |
          echo $HTML_CONTENT
