name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch where your file is located

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create deployment branch
      run: git checkout -b deploy  # Change this to the branch name you want to create

    - name: Deploy to GitHub Pages
      run: |
        rsync -q -av --checksum --progress ./ github-pages-deploy-action-temp-deployment-folder --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github --exclude generate_table.py
      env:
        ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}  # secret personal token for repo access

    - name: Commit and push changes
      run: |
        cd github-pages-deploy-action-temp-deployment-folder
        git config user.name 'devesh-joshi'
        git config user.email 'devesh.joshi@phlips.com'
        git add .
        git commit --no-verify --allow-empty -m "Deploy to GitHub Pages"
        git push --force origin deploy  # Change this to the branch where you want to deploy
