name: Generate HTML

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch file from repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install csvkit

      - name: Process data and generate HTML
        run: |
          python process_data.py

      - name: Publish HTML file
        uses: actions/upload-artifact@v2
        with:
          name: html-file
          path: result.html
