name: Generate HTML

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch file from repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install csvkit

      - name: Process data and generate HTML
        run: |
          python process_data.py -o /home/runner/work/S3-Html/S3-Html
          # echo "::set-output name=html_content::$(cat result.html)"
          echo "{html_content}={cat result.html}" >> $GITHUB_STATE

      - name: Publish HTML content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          htmlContent="${{ steps.publish_html.outputs.html_content }}"
          echo "$htmlContent" > html_content.html

      - name: Show HTML content
        run: |
          cat html_content.html
