name: Generate HTML

on:
  push:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch file from repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install csvkit

      - name: Process data and generate HTML
        id: publish_html
        run: |
          python process_data.py
          echo "html_content=$(cat result.html)" >> $GITHUB_ENV

      - name: Publish HTML content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          htmlContent=${{ env.html_content }}
          echo "$htmlContent" > html_content.html

      - name: Show HTML content
        run: |
          cat html_content.html
