name: Create HTML file

on:
  push:
    branches:
      - main

jobs:
  create-html-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the path to the file
        run: echo "FILE_PATH=$(find . -name app_final_result.txt)"
      - name: Download the file
        run: wget -O app_final_result.txt $FILE_PATH
      # - name: Get the S3 bucket name
      #   run: echo "S3_BUCKET_NAME=$(aws s3 ls | awk '/app_final_result.txt/ {print <span class="math-inline">3\}\'\)"
      # - name\: Download the file from S3
      #   run\: aws s3 cp s3\://</span>{S3_BUCKET_NAME}/app_final_result.txt .
      - name: Create the HTML file
        run: |
          echo "<html>" > result.html
          echo "<head>" >> result.html
          echo "<title>Result</title>" >> result.html
          echo "</head>" >> result.html
          echo "<body>" >> result.html
          echo "<table>" >> result.html
          echo "<tr>" >> result.html
          echo "<th>Application</th>" >> result.html
          echo "<th>Region</th>" >> result.html
          echo "<th>Version</th>" >> result.html
          echo "<th>Result</th>" >> result.html
          echo "</tr>" >> result.html
          while read -r line; do
            echo "<tr>" >> result.html
            echo "<td>$line</td>" >> result.html
            echo "</tr>" >> result.html
          done < app_final_result.txt
          echo "</table>" >> result.html
          echo "</body>" >> result.html
          echo "</html>" >> result.html
      - name: Show the HTML file
        run: open result.html
